spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bestfood?serverTimezone=UTC
    username: ssafy
    password: ssafy
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
  security:
    user:
      name: test
      password: test
    
server:
  port: 9090
  